### ISSUE TITLE
Add support for Arch Linux

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sadbro/pydirman#11]
**Is your feature request related to a problem? Please describe.**
Currently, the setup.py file will only work for Debian based distros which use apt as their package manager. Other Linux users will have to manually setup Pydirman. :(

**Describe the solution you'd like**
Improve the setup.py file to add support for Arch Linux along with Debian Linux.

**Describe alternatives you've considered**
Writing separate setup files for different distros, but it won't be necessary unless we are adding support for a lot of distros.

**Additional context**

**Comment by sahil-sagwekar2652** [comment]
@sadbro Please assign this issue to me, I am working on this issue.

**Comment by sadbro** [comment]
@sahil-sagwekar2652 Do drop a pull request when you are done with the Arch version. No rush tho ;)
