### ISSUE TITLE
Create a new window to handle the output of the 'test' command

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sadbro/pydirman#16]
**Is your feature request related to a problem? Please describe.**
The current version of pydirman lets you test one file at a time and the output is printed in the same window. This is a problem when we are working with multiple files at the same time.

**Describe the solution you'd like**
Create a new terminal window which runs the 'test' command interface for the chosen file.

**Comment by sadbro** [comment]
I have thought about it, ispe baad me meet me baith te hai
